### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by jarrettj** [soroushatarod/terraform-aws-cloudfront-wordpress#4]
Hi

Good day.

How would one add logging? Thanks.

Regards.

**Comment by soroushatarod** [comment]
@jarrettj you would need to add https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#logging_config . Would be happy to receive a PR or I could update the code during the weekend :)

**Comment by jarrettj** [comment]
Thanks, will add myself when I get a chance. Have a workaround :)
